### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by cgyan009** [ngageoint/geopackage-ios#27]
there is link error during build in Xcode 8.2

**Comment by bosborn** [comment]
Migrated the Podfile for CocoaPods and removed the extra libPod reference (2522ea5).

Let me know if that fixes your issue.

**Comment by cgyan009** [comment]
Hi Brian,

I am going to access local mbtiles. Is Geopackage IOS capable to do this?

Many thanks,

**Comment by bosborn** [comment]
The scope of GeoPackage iOS is only for GeoPackages.  You would need to convert the MBTiles to a GeoPackage first.  An MBTiles to GeoPackage conversion could be written using GeoPackage iOS if you did not have an alternative method.

@danielbarela wrote us [a converter](https://github.com/ngageoint/geopackage-js/tree/master/converters/mbtiles) in our [geopackage-js](https://github.com/ngageoint/geopackage-js) library which can be run from a browser or command line.

**Comment by cgyan009** [comment]
Hi Brian,

it still can not compile in Xcode 8.2

**Comment by danielbarela** [comment]
What version of CocoaPods are you using and can you please post the error you are seeing?

**Comment by cgyan009** [comment]
the version is 1.1.1

**Comment by bosborn** [comment]
Can you provide the error you are seeing and the steps you are trying?

In a fresh clone or download of geopackage-ios master:

`pod install`
`open geopackage-ios.xcworkspace`

Not seeing any compile errors in Xcode 8.2.1 using CocoaPods 1.1.1.

**Comment by cgyan009** [comment]
somehow, geopackage-ios.xcworkspace is not generated.

**Comment by bosborn** [comment]
It's hard to even guess unless you can provide some output.

`pod install --verbose`

**Comment by cgyan009** [comment]
below is the message of pod install

wildcat:geopackage-mapcache-ios-master frankyan$ pod install

Analyzing dependencies

Downloading dependencies

Using AFNetworking (3.1.0)

Using geopackage-ios (1.2.0)

Using proj4 (4.8.0)

Using wkb-ios (1.0.6)

Generating Pods project

Integrating client project

Sending stats

Pod installation complete! There is 1 dependency from the Podfile and 4
total pods installed.


[!] Your Podfile has had smart quotes sanitised. To avoid issues in the
future, you should not use TextEdit for editing it. If you are not using
TextEdit, you should turn off smart quotes in your editor of choice.


[!] The `mapcache-ios [Release]` target overrides the `OTHER_LDFLAGS` build
setting defined in `Pods/Target Support
Files/Pods-mapcache-ios/Pods-mapcache-ios.release.xcconfig'. This can lead
to problems with the CocoaPods installation

    - Use the `$(inherited)` flag, or

    - Remove the build settings from the target.

wildcat:geopackage-mapcache-ios-master frankyan$

**Comment by bosborn** [comment]
So it looks like you are trying to build [geopackage-mapcache-ios](https://github.com/ngageoint/geopackage-mapcache-ios) which I hadn't fixed yet.  Since you wrote the ticket here in [geopackage-ios](https://github.com/ngageoint/geopackage-ios), I assumed you were trying to build this project.

I upgraded the Podfile and fixed the libPods link error in  geopackage-mapcache-ios [here](https://github.com/ngageoint/geopackage-mapcache-ios/commit/b05b7a8e01c5277c7a6ebe3f81f4e0bd900ed853).

With a fresh clone or [download](https://github.com/ngageoint/geopackage-mapcache-ios/archive/master.zip) of geopackage-mapcache-ios.

`pod install --verbose`
`open mapcache-ios.xcworkspace`

**Comment by bosborn** [comment]
Successfully tested building & running geopackage-ios and [geopackage-mapcache-ios](https://github.com/ngageoint/geopackage-mapcache-ios) with new [1.2.1](https://github.com/ngageoint/geopackage-ios/releases/tag/1.2.1) release using CocoaPods 1.1.1 and Xcode 8.2.1.

**Comment by cgyan009** [comment]
Cool, thank you every much.
Have a nice day.

2017年2月2日 09:58，"Brian Osborn" <notifications@github.com>写道：
