### ISSUE TITLE
Why cocoapods installs 3.2.0?

### ISSUE THREAD

**Issue by livebird** [ngageoint/geopackage-ios#43]
When I put `geopackage-ios~> 3.3.0` in the Pod file it show error 

**"[!] Unable to find a specification for `geopackage-ios~> 3.3.0`"**

When I removed '~> 3.3.0' from Pod file it automatically takes version 3.2.0.

Please help.

**Comment by bosborn** [comment]
Try updating your local repos
`pod repo update`
