### ISSUE TITLE
Result count computation fails

### ISSUE THREAD

**Issue by userFortyTwo** [ngageoint/geopackage-ios#51]
The `+[GPKGSqlUtils countWithDatabase:andStatement:andArgs:]` method fails to provide the number of rows matching the given SQL query if the table being queried has a column with the letters "from" in its name.

For example, if the `statement` equals `select "id", "convertFrom", "type" from "myTable" where "id" = ?`, the count query will be determined to be `SELECT COUNT(*) From", "type" from "myTable" where "id" = ?` and thus fail to be executed.

**Comment by bosborn** [comment]
[Fixed](https://github.com/ngageoint/geopackage-ios/commit/2e40f24d9a48fcb4039d1ae3d4020ce970b131a5) in version [7.3.0](https://github.com/ngageoint/geopackage-ios/releases/tag/7.3.0)

**Comment by userFortyTwo** [comment]
Great, thanks!
